// ISIC Rev.4 division titles (shortened for chart labels).
export const ISIC_DIVISION_LABELS: Record<string, string> = {
  '01': 'Crop & animal production', '02': 'Forestry & logging', '03': 'Fishing & aquaculture',
  '05': 'Coal mining', '06': 'Crude petroleum & natural gas', '07': 'Metal ore mining', '08': 'Other mining & quarrying', '09': 'Mining support services',
  '10': 'Food products', '11': 'Beverages', '12': 'Tobacco products', '13': 'Textiles', '14': 'Wearing apparel', '15': 'Leather products',
  '16': 'Wood products', '17': 'Paper products', '18': 'Printing', '19': 'Coke & refined petroleum', '20': 'Chemicals', '21': 'Pharmaceuticals',
  '22': 'Rubber & plastics', '23': 'Non-metallic minerals', '24': 'Basic metals', '25': 'Fabricated metal products', '26': 'Computer & electronics',
  '27': 'Electrical equipment', '28': 'Machinery', '29': 'Motor vehicles', '30': 'Other transport equipment', '31': 'Furniture',
  '32': 'Other manufacturing', '33': 'Repair & installation of machinery',
  '35': 'Electricity, gas & steam',
  '36': 'Water supply', '37': 'Sewerage', '38': 'Waste management', '39': 'Remediation',
  '41': 'Construction of buildings', '42': 'Civil engineering', '43': 'Specialised construction',
  '45': 'Motor vehicle trade & repair', '46': 'Wholesale trade', '47': 'Retail trade',
  '49': 'Land transport', '50': 'Water transport', '51': 'Air transport', '52': 'Warehousing & support', '53': 'Postal & courier',
  '55': 'Accommodation', '56': 'Food & beverage services',
  '58': 'Publishing', '59': 'Film, video & music', '60': 'Broadcasting', '61': 'Telecommunications', '62': 'Computer programming', '63': 'Information services',
  '64': 'Financial services', '65': 'Insurance & pensions', '66': 'Auxiliary financial services',
  '68': 'Real estate',
  '69': 'Legal & accounting', '70': 'Head offices & consultancy', '71': 'Architecture & engineering', '72': 'Scientific R&D', '73': 'Advertising & market research',
  '74': 'Other professional activities', '75': 'Veterinary',
  '77': 'Rental & leasing', '78': 'Employment activities', '79': 'Travel agencies', '80': 'Security & investigation', '81': 'Building & landscape services',
  '82': 'Office & business support',
  '84': 'Public administration & defence',
  '85': 'Education',
  '86': 'Human health', '87': 'Residential care', '88': 'Social work',
  '90': 'Creative & arts', '91': 'Libraries & museums', '92': 'Gambling', '93': 'Sports & recreation',
  '94': 'Membership organisations', '95': 'Repair of household goods', '96': 'Other personal services',
  '97': 'Households as employers', '98': 'Household own-use production',
  '99': 'Extraterritorial organisations',
};

export const ISIC_DIVISION_LABELS_AR: Record<string, string> = {
  '01': 'الإنتاج النباتي والحيواني', '02': 'الحراجة وقطع الأخشاب', '03': 'صيد الأسماك وتربية المائيات',
  '05': 'تعدين الفحم', '06': 'النفط الخام والغاز الطبيعي', '07': 'تعدين الركازات الفلزية', '08': 'أنشطة التعدين واستغلال المحاجر الأخرى', '09': 'خدمات دعم التعدين',
  '10': 'المنتجات الغذائية', '11': 'المشروبات', '12': 'منتجات التبغ', '13': 'المنسوجات', '14': 'الملبوسات', '15': 'المنتجات الجلدية',
  '16': 'منتجات الخشب', '17': 'منتجات الورق', '18': 'الطباعة', '19': 'فحم الكوك والمنتجات النفطية المكررة', '20': 'المواد الكيميائية', '21': 'المستحضرات الصيدلانية',
  '22': 'المطاط واللدائن', '23': 'منتجات المعادن اللافلزية', '24': 'الفلزات القاعدية', '25': 'المنتجات المعدنية المشكّلة', '26': 'الحواسيب والإلكترونيات',
  '27': 'المعدات الكهربائية', '28': 'الآلات والمعدات', '29': 'المركبات ذات المحركات', '30': 'معدات النقل الأخرى', '31': 'الأثاث',
  '32': 'الصناعات التحويلية الأخرى', '33': 'إصلاح الآلات وتركيبها',
  '35': 'الكهرباء والغاز والبخار',
  '36': 'إمدادات المياه', '37': 'الصرف الصحي', '38': 'إدارة النفايات', '39': 'أنشطة المعالجة',
  '41': 'تشييد المباني', '42': 'الهندسة المدنية', '43': 'أنشطة التشييد المتخصصة',
  '45': 'تجارة المركبات وإصلاحها', '46': 'تجارة الجملة', '47': 'تجارة التجزئة',
  '49': 'النقل البري', '50': 'النقل المائي', '51': 'النقل الجوي', '52': 'التخزين وأنشطة الدعم', '53': 'البريد والتوصيل',
  '55': 'الإقامة', '56': 'خدمات الطعام والمشروبات',
  '58': 'النشر', '59': 'الأفلام والفيديو والموسيقى', '60': 'البث', '61': 'الاتصالات', '62': 'البرمجة الحاسوبية', '63': 'خدمات المعلومات',
  '64': 'الخدمات المالية', '65': 'التأمين والمعاشات', '66': 'الخدمات المالية المساعدة',
  '68': 'الأنشطة العقارية',
  '69': 'الأنشطة القانونية والمحاسبية', '70': 'المكاتب الرئيسية والاستشارات', '71': 'الهندسة المعمارية والهندسة', '72': 'البحث والتطوير العلمي', '73': 'الإعلان وأبحاث السوق',
  '74': 'الأنشطة المهنية الأخرى', '75': 'الأنشطة البيطرية',
  '77': 'التأجير', '78': 'أنشطة التوظيف', '79': 'وكالات السفر', '80': 'الأمن والتحقيقات', '81': 'خدمات المباني والمناظر الطبيعية',
  '82': 'دعم المكاتب والأعمال',
  '84': 'الإدارة العامة والدفاع',
  '85': 'التعليم',
  '86': 'الصحة البشرية', '87': 'الرعاية المقيمة', '88': 'العمل الاجتماعي',
  '90': 'الأنشطة الإبداعية والفنون', '91': 'المكتبات والمتاحف', '92': 'المقامرة', '93': 'الرياضة والترفيه',
  '94': 'المنظمات ذات العضوية', '95': 'إصلاح السلع المنزلية', '96': 'الخدمات الشخصية الأخرى',
  '97': 'الأسر المعيشية كأصحاب عمل', '98': 'إنتاج الأسر لاستخدامها الخاص',
  '99': 'المنظمات الخارجية',
};
