[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/next"

[context.production]
command = "npm run build"

[context.preview]
command = "npm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
